# Generated by Django 6.0.1 on 2026-01-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('WEB', 'Developpement web'), ('GRAPHIC', 'Design graphique')], max_length=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('live_url', models.URLField(blank=True, help_text='Lien vers le site', null=True)),
                ('github_url', models.URLField(blank=True, help_text='Lien vers le Github', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
